version: '3'

services:
  redis1:
    image: 'redis:6.2.6'
    container_name: 'redis1'
    command: ["redis-server", "--save", "60", "1", "--appendonly", "yes", "--maxmemory", "1g", "--maxmemory-policy", "allkeys-lfu"]
    ports:
      - '6381:6379'  # Puerto personalizado para el servidor Redis1
    networks:
      - redis_network

  redis2:
    image: 'redis:6.2.6'
    container_name: 'redis2'
    command: ["redis-server", "--save", "60", "1", "--appendonly", "yes", "--maxmemory", "1g", "--maxmemory-policy", "allkeys-lfu"]
    ports:
      - '6382:6379'  # Puerto personalizado para el servidor Redis2
    networks:
      - redis_network

  redis3:
    image: 'redis:6.2.6'
    container_name: 'redis3'
    command: ["redis-server", "--save", "60", "1", "--appendonly", "yes", "--maxmemory", "1g", "--maxmemory-policy", "allkeys-lfu"]
    ports:
      - '6383:6379'  # Puerto personalizado para el servidor Redis3
    networks:
      - redis_network

networks:
  redis_network:
    driver: bridge

